name: Deploy to VPS

on:
  push:
    branches: [ main ] # Sesuaikan dengan branch utama Anda (misal: main atau master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS via SSH
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USER: ${{ secrets.SSH_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          set -e
          cd /home/ubuntu/nora-vue-golang
          git pull origin main
          cd backend-go
          /usr/local/go/bin/go build -o server-bin ./cmd/server
          sudo systemctl restart golang-app.service
        EOF